api/urls.py
from django.urls import path
from . import views
from rest_framework.authtoken.views import obtain_auth_token


app_name = 'api'

urlpatterns = [
    path('products/', views.ProductListView.as_view(), name="product-list"),
    path('token/', views.AdminObtainAuthToken.as_view()),
    path('products/<int:product_pk>', views.ProductDetailView.as_view(), name="product-detail"),
    path('products/<int:product_pk>/<int:product_specific_pk>', views.ProductSpecificDetailView.as_view(),
         name="product-specific-detail"),
]

pages/urls.py
from django.urls import path
from . import views
app_name = 'pages'
urlpatterns = [
    path('', views.home_view, name='home'),
]

products/urls.py
from django.urls import path
from django.conf import settings
from . import views

app_name = 'products'
urlpatterns = [
    path('<int:pk>', views.product_detail_view, name='detail'),
    path('<int:pk>/rate', views.product_rate_view, name='rate'),
    path('cart/', views.cart_view, name='cart'),
    path('cart/clear', views.clear_cart_view, name='clear-cart'),
    path('cart/add/<int:p_id>/<int:ps_id>', views.add_cart_view, name='add-cart'),
    path('cart/remove/<int:p_id>/<int:ps_id>', views.remove_cart_view, name='remove-cart'),
    path('type/<int:product_type>', views.product_type_view, name='type')
]

shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('products/', include('products.urls')),
    path('orders/', include('orders.urls')),
    path('users/', include('users.urls')),
    path('', include('pages.urls')),
    path('api/', include('api.urls')),
]
#img patterns
if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
    path('login', views.login_view, name='login'),
    path('logout', views.logout_view, name='logout'),
    path('register', views.register_view, name='register'),
    path('nologin', views.no_login_order, name='nologin'),
    path('change_password/<slug:uidb64>', views.change_password_view, name='change_password'),
    path('change_data/<slug:uidb64>', views.change_data_view, name='change_data'),
    path('reset/email', views.reset_insert_email_view, name='reset_insert_email'),
    path('reset/<slug:uidb64>/<slug:token>', views.reset_new_password_view, name='reset_new_password'),
    path('activate/<slug:uidb64>/<slug:token>', views.account_activate_view, name='account_activate'),
    path('orders/<slug:uidb64>', views.users_orders_list, name='orders_list')
]

pages/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">


    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    {% if title %}
    <title>{{ title }}</title>
    {% else %}
    <title> Shop </title>
    {% endif %}
    <style>
    .star-rating::before {
      content: "⭐⭐⭐⭐⭐";
    }

    .star-rating {
        display: inline-block;
        background-clip: text;
        -webkit-background-clip: text;
        color: rgba(0, 0, 0, 0.1);
    }
    </style>
    {% load static %}
    <link rel="shortcut icon" type="image/png" href="{% static 'images/favicon.ico' %}" >
    {% block head_extra %} {% endblock %}
</head>
<body>

    {% include 'navbar.html' %}
    {% block sidebar %} {% endblock sidebar %}
    <div class="container">
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{message.tags}} ">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
    {% block content %} {% endblock content %}
    </div>
    <div class="container my-3">
        <center>This is an educational project. Not a real shop. Payments aren't processed and products won't be delivered.</center>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.7/dist/umd/popper.min.js" integrity="sha384-zYPOMqeu1DAVkHiLqWBUTcbYfZ8osu1Nd6Z89ify25QV9guujx43ITvfi12/QExE" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.min.js" integrity="sha384-Y4oOpwW3duJdCWv5ly8SCFYWqFDsfob/3GkgExXKV4idmbt98QcxXYs9UoXAB7BZ" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
</body>
</html>

pages/templates/navbar.html
<style>
    .badge_cart:after{
        content:attr(value);
        font-size:12px;
        color: #fff;
        background: red;
        border-radius:50%;
        padding: 0 5px;
        position:relative;
        left:-8px;
        top:-10px;
        opacity:0.9;
    }
</style>



<nav class="navbar bg-dark navbar-expand-lg bg-body-tertiary"  data-bs-theme="dark">
  <div class="container-fluid">
    <img src="/static/images/favicon.ico" alt="MyShop" width="30">
    <a class="navbar-brand" href="{% url 'pages:home' %}">MyShop</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'pages:home' %}">Home</a>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Products
          </a>
          <ul class="dropdown-menu">
            {% if product_types %}
              {% for key, type in product_types.items %}
                <li><a class="dropdown-item" href="{% url 'products:type' key %}">{{type}}s</a></li>
              {% endfor %}
            {% endif %}
          </ul>
      </li>
      </ul>
    </div>
  </div>
  <div class="collapse navbar-collapse me-auto" id="navbarNavRight">
    <ul class="navbar-nav ">
      {% if request.user.is_authenticated %}
      <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            {{request.user.username}}
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'users:orders_list' uidb64 %}">My orders</a></li>
            <li><a class="dropdown-item" href="{% url 'users:change_data' uidb64 %}">Change user data</a></li>
            <li><a class="dropdown-item" href="{% url 'users:change_password' uidb64 %}">Change password</a></li>
          </ul>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'users:logout' %}">Logout</a>
      </li>
      {% else %}
        <li class="nav-item">
        <a class="nav-link" href="{% url 'users:login' %}">Login</a>
      </li>
      {% endif %}
    </ul>

    <ul class="navbar-nav">
      {% if request.session.cart and request.session.cart_length %}
      <li class="nav-item">
        <a href="{% url 'products:cart' %}"><i class="fa badge_cart fa-lg" value={{request.session.cart_length}}>&#xf07a;</i></a>
      </li>
      {% else %}
      <li class="nav-item">
         <a href="{% url 'products:cart' %}"><i class="fa badge_cart fa-lg" value=0>&#xf07a;</i></a>
      </li>
      {% endif %}
    </ul>
  </div>
</nav>