api/urls.py
from django.urls import path
from . import views
from rest_framework.authtoken.views import obtain_auth_token


app_name = 'api'

urlpatterns = [
    path('products/', views.ProductListView.as_view(), name="product-list"),
    path('token/', views.AdminObtainAuthToken.as_view()),
    path('products/<int:product_pk>', views.ProductDetailView.as_view(), name="product-detail"),
    path('products/<int:product_pk>/<int:product_specific_pk>', views.ProductSpecificDetailView.as_view(),
         name="product-specific-detail"),
]

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'
urlpatterns = [
    path('data/', views.order_data_view, name='data'),
    path('<int:pk>/', views.order_detail_view, name='detail'),
    path('confirm/<slug:oidb64>/<slug:token>', views.order_confirm_view, name='confirm'),
    path('checkout/success', views.checkout_successful_view, name='checkout_success'),
    path('checkout/cancelled', views.checkout_cancelled_view, name='checkout_cancelled'),
    path('webhooks/stripe/', views.stripe_webhook, name='stripe_webhook')
]

shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('products/', include('products.urls')),
    path('orders/', include('orders.urls')),
    path('users/', include('users.urls')),
    path('', include('pages.urls')),
    path('api/', include('api.urls')),
]
#img patterns
if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
    path('login', views.login_view, name='login'),
    path('logout', views.logout_view, name='logout'),
    path('register', views.register_view, name='register'),
    path('nologin', views.no_login_order, name='nologin'),
    path('change_password/<slug:uidb64>', views.change_password_view, name='change_password'),
    path('change_data/<slug:uidb64>', views.change_data_view, name='change_data'),
    path('reset/email', views.reset_insert_email_view, name='reset_insert_email'),
    path('reset/<slug:uidb64>/<slug:token>', views.reset_new_password_view, name='reset_new_password'),
    path('activate/<slug:uidb64>/<slug:token>', views.account_activate_view, name='account_activate'),
    path('orders/<slug:uidb64>', views.users_orders_list, name='orders_list')
]

orders/models.py
from django.db import models
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.contrib.auth.models import User
from django.core.mail import send_mail
from .token_generator import order_confirmation_token_generator
from django.utils.http import urlsafe_base64_encode
from django.shortcuts import reverse
from django.db.models import Sum

# Create your models here.


class Order(models.Model):
    WAIT_PAYMENT = "1"
    WAIT_SENDING = "2"
    SENT = "3"
    DELIVERED = "4"
    STATUS_CHOICES = [
        (WAIT_PAYMENT, "Waiting for payment"),
        (WAIT_SENDING, "Waiting for sending"),
        (SENT, "Sent"),
        (DELIVERED, "Delivered"),]
    email = models.EmailField()
    user = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    state = models.CharField(max_length=50)
    city = models.CharField(max_length=50)
    street = models.CharField(max_length=50)
    number = models.CharField(max_length=50)
    postal_code = models.CharField(max_length=50)
    status = models.CharField(choices=STATUS_CHOICES, default=WAIT_PAYMENT, max_length=40)
    confirmed = models.BooleanField(default=False)
    stripe_checkout_id = models.CharField(max_length=220, blank=True, null=True)

    def __str__(self):
        return f"{self.id}-{self.email}"

    def __iter__(self):
        for field in self._meta.fields:
            name = field.verbose_name.capitalize()
            value = field.value_to_string(self)
            if field.choices is not None:
                f_name = 'get_' + field.name + '_display'
                display = getattr(self, f_name)
                value = display()
            if name.lower() in ['id', 'user', 'created', 'modified', 'stripe checkout id']:
                continue
            yield (name, value)

    def get_order_data(self):
        order_data = []
        for field in self:
            order_data.append(field)
        return order_data

    def send_to_user(self, request, checkout_url=None):
        # Send email to user with order data and confirmation link if necessary. If order is already confirmed send
        # checkout_url to complete payment.
        subject = f"Your Order nr: {self.id}"
        message = f"Your order number {self.id} has been created. Order data:\n"
        for data in self.get_order_data():
            message += f"{data[0]}: {data[1]}\n"
        message += "List of products: \n"
        i = 1
        for order_product in self.order_products.all():
            message += f"{i}. {str(order_product.product_specific)} Amount: {order_product.amount}\n"
            i += 1
        if not self.confirmed:
            oidb64 = urlsafe_base64_encode(str(self.id).encode())
            token = order_confirmation_token_generator.make_token(self)
            url = request.build_absolute_uri(f'/orders/confirm/{oidb64}/{token}')
            message += f"\nYour order is not confirmed. Follow this link to confirm it:\n"
            message += url
            subject += " (Unconfirmed)"
        elif checkout_url is not None:
            message += f"\nYour order is confirmed. Link to payment:\n"
            message += checkout_url
        send_mail(subject=subject, message=message, from_email="Django MyShop", recipient_list=[self.email])

    def send_confirmation_ok_email(self, checkout_url):
        subject = f"Your Order nr: {self.id} is now confirmed."
        message = f"Your order has been successfully confirmed."
        if checkout_url is not None:
            message += f"\nLink to payment:\n"
            message += checkout_url
        send_mail(subject=subject, message=message, from_email="Django MyShop", recipient_list=[self.email])

    def send_payment_ok_email(self):
        subject = f"Order nr: {self.id} payment was successful."
        message = f"Payment for order nr: {self.id} was received.\nYour Django MyShop team."
        send_mail(subject=subject, message=message, from_email="Django MyShop", recipient_list=[self.email])

    @property
    def total_value(self):
        value = 0
        products = self.order_products.all()
        for product in products:
            value += product.product_price
        return value

    @property
    def total_items(self):
        return self.order_products.all().aggregate(Sum('amount')).get('amount__sum',0)

    def get_absolute_url(self):
        return reverse('orders:detail', kwargs={"pk": self.pk})


class OrderProducts(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name="order_products")
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    product_specific = GenericForeignKey("content_type", "object_id")
    amount = models.PositiveIntegerField(default=1)
    product_name = models.CharField(max_length=100, default='', blank=True)
    product_price = models.DecimalField(default=0, blank=True, max_digits=10, decimal_places=2)

    class Meta:
        verbose_name_plural = "OrderProducts"

    def save(self, create=False, **kwargs):
        # Save current product name and price in database(in case price changes in the future).
        # Only during order creation - create=True.
        if self.product_specific is not None and create:
            self.product_name = str(self.product_specific)
            try:
                self.product_price = self.product_specific.product.current_price
            except AttributeError:
                pass
        super().save(**kwargs)

    def __str__(self):
        return f"Order:{self.order.id}-{self.product_name}"

orders/forms.py
from django.forms import ModelForm
from .models import Order


class OrderForm(ModelForm):

    class Meta:
        model = Order
        exclude = ['user', 'product_count', 'total', 'status', 'confirmed', 'stripe_checkout_id']

users/forms.py
from django import forms
from .models import UserData
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User



class ResetForm(forms.Form):
    email = forms.EmailField()

class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)


class UserForm(UserCreationForm):
    email = forms.EmailField()
    first_name = forms.CharField(max_length=150, required=False)
    last_name = forms.CharField(max_length=150, required=False)

    class Meta:
        fields = ("username", "password1", "password2", "email", "first_name", "last_name")
        model = User


class UserChangeForm(forms.ModelForm):
    class Meta:
        fields = ("email", "first_name", "last_name")
        model = User

class UserDataForm(forms.ModelForm):

    class Meta:
        model = UserData
        exclude = ['user', 'is_active']

orders/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404, HttpResponse
from products import cart
from .models import Order, OrderProducts
from django.contrib import messages
from .forms import OrderForm
from django.conf import settings
from django.contrib.auth.models import User
from django.forms.models import model_to_dict
from django.apps import apps
from django.db.models import ObjectDoesNotExist
from django.http import HttpResponseForbidden
from django.utils.http import urlsafe_base64_decode
from .token_generator import order_confirmation_token_generator
from django.http import HttpResponseNotFound
from django.utils import timezone
import stripe
from django.views.decorators.csrf import csrf_exempt
# Create your views here.

UserData = apps.get_model('users', 'UserData')

stripe.api_key = settings.STRIPE_SECRET_KEY


def create_checkout(request, order_object_id):
    try:
        order = Order.objects.get(id=order_object_id)
    except (ValueError, ObjectDoesNotExist):
        return None
    # Create stripe checkout session if order is confirmed.
    if order.confirmed:
        line_items = []
        for product in order.order_products.all():
            if product.product_specific.stripe_price_id is not None:
                line_items.append(
                    {
                        'price': product.product_specific.stripe_price_id,
                        'quantity': product.amount
                    }
                )
        success_url = request.build_absolute_uri(reverse('orders:checkout_success'))
        cancel_url = request.build_absolute_uri(reverse('orders:checkout_cancelled'))
        if line_items:
            stripe_checkout_session = stripe.checkout.Session.create(
                line_items=line_items,
                mode="payment",
                success_url=success_url,
                cancel_url=cancel_url,
                customer_email=order.email,
            )
            order.stripe_checkout_id = stripe_checkout_session.stripe_id
            order.save()
            return stripe_checkout_session.url
    return None


def order_data_view(request):
    ORDER_COOLDOWN_SEC = 60
    # get order data and create order
    user_object = None
    if request.user.is_authenticated:
        user_object = User.objects.get(id=request.user.id)
    # user logged in or selected to order without login
    if user_object is None and not request.session.get('no_login_order', False):
        url = settings.LOGIN_URL + '?next=' + request.path + '&order=True'
        return redirect(url)
    # redirect if cart is empty
    products = cart.get_cart_products_specific_list(request)
    if len(products) == 0:
        messages.warning(request, "No products to order.")
        return redirect('pages:home')
    form = OrderForm(request.POST or None)
    # get user data and put into initial form
    if request.method == "GET" and user_object is not None:
        data = model_to_dict(user_object, fields=['email', 'first_name', 'last_name'])
        try:
            user_data_object = UserData.objects.get(user=user_object)
            data.update(model_to_dict(user_data_object))
        except ObjectDoesNotExist:
            pass
        form.initial = data
    elif request.method == "POST":
        if form.is_valid():
            # Check if last order on this email address was created after cooldown time to prevent duplicate orders.
            try:
                last_order = Order.objects.filter(email=form.cleaned_data['email']).latest('created')
                if (timezone.now() - last_order.created).seconds < ORDER_COOLDOWN_SEC:
                    messages.warning(request, "You can't create another order so quickly.")
                    return redirect('pages:home')
            except ObjectDoesNotExist:
                pass
            order_object = form.save(commit=False)
            # if user is logged in order is automatically confirmed and user is assigned
            if user_object is not None:
                order_object.user = user_object
                order_object.confirmed = True
            order_object.save()
            # Create order products, not using bulk_create to call save method
            for product, amount in products:
                order_product = OrderProducts(order=order_object, product_specific=product, amount=amount)
                order_product.save(create=True)
            checkout_session_url = create_checkout(request, order_object.id)
            order_object.send_to_user(request,  checkout_session_url)
            messages.success(request, f"Your order number {order_object.id} has been created.")
            cart.clear_cart(request)
            if checkout_session_url is not None:
                return redirect(checkout_session_url)
            else:
                messages.warning(request, "Confirm your order to checkout.")
                return redirect('pages:home')
        else:
            messages.warning(request, "Wrong data inserted.")
    context = {
        'title': 'Order data',
        'form': form
    }
    return render(request, 'orders/order_data.html', context)


def order_detail_view(request, pk):
    order_object = get_object_or_404(Order, pk=pk)
    # Check if user is authenticated.
    if not request.user.is_authenticated:
        # redirect to login page
        messages.warning(request, "Login required.")
        url = settings.LOGIN_URL + '?next=' + request.path
        return redirect(url)
    # Check if user is authorized to access this page.
    elif order_object.user is None or order_object.user.id != request.user.id:
        return HttpResponseForbidden(request)
    context = {
        'title': 'Order details',
        'order': order_object,
    }
    return render(request, 'orders/order_detail.html', context)


def order_confirm_view(request, oidb64, token):
    # Get order from base 64 encoded oidb64.
    try:
        order_id = urlsafe_base64_decode(oidb64)
        order = Order.objects.get(id=order_id)
    except (ValueError, ObjectDoesNotExist):
        return HttpResponseNotFound(request)

    if order.confirmed:
        messages.success(request, "Order already confirmed.")
    # Check provided token.
    elif order_confirmation_token_generator.check_token(order, token):
        order.confirmed = True
        order.save()
        checkout_session_url = create_checkout(request, order_id)
        order.send_confirmation_ok_email(checkout_session_url)
        if checkout_session_url is not None:
            return redirect(checkout_session_url)
    else:
        return HttpResponse('401 Unauthorized. Token error.', status=401)
    return redirect('pages:home')


def checkout_successful_view(request):
    return render(request, 'orders/checkout_successful.html')


def checkout_cancelled_view(request):
    return render(request, 'orders/checkout_cancelled.html')


@csrf_exempt
def stripe_webhook(request):
    payload = request.body
    sig_header = request.META['HTTP_STRIPE_SIGNATURE']
    event = None
    try:
        event = stripe.Webhook.construct_event(
            payload, sig_header, settings.STRIPE_WEBHOOK_SECRET
        )
    except ValueError as e:
        # Invalid payload
        return HttpResponse(status=400)
    except stripe.error.SignatureVerificationError as e:
        # Invalid signature
        return HttpResponse(status=400)
    # Handle the checkout.session.completed event
    if event['type'] == 'checkout.session.completed':
        data_object = event['data']['object']
        email = data_object.get('customer_email')
        checkout_id = data_object.get('id')
        try:
            order_object = Order.objects.get(email=email, stripe_checkout_id=checkout_id)
        except ObjectDoesNotExist:
            # No object found.
            return HttpResponse(status=400)
        # Change order status and send email confirmation to user.
        order_object.status = order_object.WAIT_SENDING
        order_object.save()
        order_object.send_payment_ok_email()
    return HttpResponse(status=200)

users/templates/users/change_password_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<h1 class="my-4">Change password:</h1>
<div class="mt-4">
    <form method="POST">
        {% csrf_token %}
        {{form|crispy}}
        <button type="submit" class="btn btn-primary my-4">Change password</button>
        <button onclick="history.back()" class="btn btn-secondary" type="button">Go back</button>
    </form>
</div>
{% endblock %}

users/templates/users/change_user_data_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<h1  class="my-4">Change User data:</h1>
<div class="mt-4">
    <form method="POST">
        {% csrf_token %}
        {{form_user|crispy}}
        {{form_user_data|crispy}}
        <button type="submit" class="btn btn-primary my-4">Change data</button>
        <button onclick="history.back()" class="btn btn-secondary" type="button">Go back</button>
    </form>
</div>
{% endblock %}

users/templates/users/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<h1  class="my-4">Login:</h1>
<div class="mt-4">
    <form method="POST">
        {% csrf_token %}
        {{form|crispy}}
        {% if request.GET.next %}
            <input type="hidden" name="next" value="{{request.GET.next}}">
        {% endif %}
        <button type="submit" class="btn btn-primary my-3">Login</button>
        <button onclick="history.back()" class="btn btn-secondary" type="button">Go back</button>
    </form>
</div>
<div class="mb-2">
    {% if request.GET.next %}
    <a href="{% url 'users:register' %}?next={{request.GET.next}}">
        <button class="btn btn-primary my-1 " type="button">Create an account</button>
    </a>
    {% else %}
    <a href="{% url 'users:register' %}">
        <button class="btn btn-primary my-1 " type="button">Create an account</button>
    </a>
    {% endif %}
</div>
<div class="my-2">
    {% if request.GET.order %}
        {% if request.GET.next %}
        <a href="{% url 'users:nologin' %}?next={{request.GET.next}}">Continue without logging in</a>
        {% else %}
        <a href="{% url 'users:nologin' %}">Continue without logging in</a>
        {% endif %}
    {% endif %}
</div>
<div class="my-2">
    <a href="{% url 'users:reset_insert_email' %}">I forgot my password</a>
</div>
{% endblock %}

users/templates/users/new_password_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<h1  class="my-4">Reset password:</h1>
<div class="mt-4">
    <form method="POST">
        {% csrf_token %}
        {{form|crispy}}
        <button type="submit" class="btn btn-primary my-4">Reset password</button>
        <button onclick="history.back()" class="btn btn-secondary" type="button">Go back</button>
    </form>
</div>
{% endblock %}

users/templates/users/orders.html
{% extends 'base.html' %}
{% block content %}
<div class="my-4">
    <h1 style="display: inline-block;">Your orders:</h1>
    <div class="dropdown float-end" style="display: inline-block;">
        <form>
          <select class="form-select" name="order" id="order" onchange="this.form.submit()" >
            <option value="" selected>Order by</option>
            <option value="1">Newest</option>
            <option value="2">Oldest</option>
            <option value="3">Highest value</option>
            <option value="4">Lowest value</option>
          </select>
        </form>
    </div>
</div>
<div class="mt-4">
    {% if orders_list %}
        <div class="list-group">
        {% for order in orders_list %}
            <a href="{{ order.get_absolute_url }}"><button type="button" class="list-group-item list-group-item-action list-group-item-info">
                Order number: <b>{{order.id}}</b> <div class="d-flex justify-content-end">  {{order.created}}</div>
                <div>Items: {{order.total_items}}  Items Value: <b>{{order.total_value}}</b></div></button></a>
        {% endfor %}
        </div>
    {% else %}
        <p>No orders found</p>
    {% endif %}
</div>
<button onclick="history.back()" class="btn btn-secondary mt-4" type="button">Go back</button>
{% endblock %}

users/templates/users/register.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<h1  class="my-4" >Register User:</h1>
<div class="mt-4">
    <form method="POST">
        {% csrf_token %}
        {{form_user|crispy}}
        {{form_user_data|crispy}}
        {% if request.GET.next %}
            <input type="hidden" name="next" value="{{request.GET.next}}">
        {% endif %}
        <button type="submit" class="btn btn-primary my-4">Register</button>
        <button onclick="history.back()" class="btn btn-secondary" type="button">Go back</button>
    </form>
</div>
{% endblock %}

users/templates/users/reset_insert_email.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<h1  class="my-4">Insert your email to reset password:</h1>
<div class="mt-4">
    <form method="POST">
        {% csrf_token %}
        {{form|crispy}}
        <button type="submit" class="btn btn-primary my-4">Reset</button>
        <button onclick="history.back()" class="btn btn-secondary" type="button">Go back</button>
    </form>
</div>
{% endblock %}