api/urls.py
from django.urls import path
from . import views
from rest_framework.authtoken.views import obtain_auth_token


app_name = 'api'

urlpatterns = [
    path('products/', views.ProductListView.as_view(), name="product-list"),
    path('token/', views.AdminObtainAuthToken.as_view()),
    path('products/<int:product_pk>', views.ProductDetailView.as_view(), name="product-detail"),
    path('products/<int:product_pk>/<int:product_specific_pk>', views.ProductSpecificDetailView.as_view(),
         name="product-specific-detail"),
]

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'
urlpatterns = [
    path('data/', views.order_data_view, name='data'),
    path('<int:pk>/', views.order_detail_view, name='detail'),
    path('confirm/<slug:oidb64>/<slug:token>', views.order_confirm_view, name='confirm'),
    path('checkout/success', views.checkout_successful_view, name='checkout_success'),
    path('checkout/cancelled', views.checkout_cancelled_view, name='checkout_cancelled'),
    path('webhooks/stripe/', views.stripe_webhook, name='stripe_webhook')
]

pages/urls.py
from django.urls import path
from . import views
app_name = 'pages'
urlpatterns = [
    path('', views.home_view, name='home'),
]

products/urls.py
from django.urls import path
from django.conf import settings
from . import views

app_name = 'products'
urlpatterns = [
    path('<int:pk>', views.product_detail_view, name='detail'),
    path('<int:pk>/rate', views.product_rate_view, name='rate'),
    path('cart/', views.cart_view, name='cart'),
    path('cart/clear', views.clear_cart_view, name='clear-cart'),
    path('cart/add/<int:p_id>/<int:ps_id>', views.add_cart_view, name='add-cart'),
    path('cart/remove/<int:p_id>/<int:ps_id>', views.remove_cart_view, name='remove-cart'),
    path('type/<int:product_type>', views.product_type_view, name='type')
]

shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('products/', include('products.urls')),
    path('orders/', include('orders.urls')),
    path('users/', include('users.urls')),
    path('', include('pages.urls')),
    path('api/', include('api.urls')),
]
#img patterns
if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/forms.py
from django.forms import ModelForm
from .models import Rating

class RatingForm(ModelForm):

    class Meta:
        model = Rating
        fields = ['value', 'comment']

products/views.py
import math

from django.shortcuts import render, redirect, get_object_or_404, get_list_or_404
from .models import Product, PRODUCT_TYPES, get_product_specific_model
from .cart import add_to_cart, clear_cart, get_cart_products_specific_list, remove_from_cart, get_cart_status
from .forms import RatingForm
from django.conf import settings
from django.contrib import messages
from django.http.response import HttpResponseNotFound
# Create your views here.


def add_cart_view(request, p_id, ps_id):
    ps = Product.get_product_specific(p_id, ps_id)
    add_to_cart(request, ps)
    return redirect('products:cart')


def remove_cart_view(request, p_id, ps_id):
    ps = Product.get_product_specific(p_id, ps_id)
    remove_from_cart(request, ps)
    return redirect('products:cart')


def cart_view(request):
    cart_products = get_cart_products_specific_list(request)
    cart_length, cart_value = get_cart_status(request)
    context = {
        'title': 'Cart',
        'cart_products': cart_products,
        'cart_length': cart_length,
        'cart_value': cart_value,
    }
    return render(request, 'products/cart.html', context)


def clear_cart_view(request):
    clear_cart(request)
    return redirect('products:cart')


def product_detail_view(request, pk):
    ORDERING = {
        '1': '-created',  # newest
        '2': 'created',  # oldest
        '3': '-value',  # highest value
        '4': 'value',   # lowest value
    }
    product = get_object_or_404(Product, pk=pk)
    product_specific = product.get_product_specific_by_attributes(request.GET)
    # Add specific product to cart and reload the page.
    if request.GET.get('add_cart', False):
        response = add_to_cart(request, product_specific)
        return response
    # Get attributes of product variants matching current selections.
    attributes = product.get_filtered_product_specific_attributes(request.GET)
    attribute_names = product.get_product_specific_model().get_lookup_names()
    # create list of images with main image as first object
    main_image = product.main_image_object
    if main_image is not None:
        other_images = list(product.images.exclude(id=main_image.id))
        images = [main_image] + other_images
    else:
        images = None
    # get ratings that involve a comment
    comments = product.ratings.exclude(comment="")
    # order comments by order parameter in query dict, default from the newest to oldest
    order = request.GET.get('order', '1')
    comments = comments.order_by(ORDERING.get(order, '-created'))
    context = {
        'title': 'Product Detail',
        'product': product,
        'images': images,
        'attributes': attributes,
        'attribute_names': attribute_names,
        'comments': comments,
        'all_selected': product_specific is not None,  # check if all attribute values has been selected
               }
    return render(request, 'products/product_detail.html', context)


def product_rate_view(request, pk):
    # check if user already rated this product
    instance = None
    if request.user.is_authenticated:
        product = get_object_or_404(Product, pk=pk)
        instance = product.ratings.filter(user=request.user).first()
    else:
        # redirect to login page
        messages.warning(request, "Login required.")
        url = settings.LOGIN_URL + '?next=' + request.path
        return redirect(url)
    form = RatingForm(request.POST or None, instance=instance)
    if request.method == 'POST':
        if form.is_valid():
            rating = form.save(commit=False)

            rating.product = product
            rating.user = request.user
            rating.save()
            return redirect('products:detail', pk=pk)
    context = {
        'title': 'Rate Product',
        'form': form
    }
    return render(request, 'products/product_rate_form.html', context)


def product_type_view(request, product_type):
    ORDERING = {
        '1': {'key': lambda x: x.current_price, 'reverse': False},  # Lowest price.
        '2': {'key': lambda x: x.current_price, 'reverse': True},  # Highest price.
        '3': {'key': lambda x: x.avg_rating, 'reverse': True},   # Best rating.
        '4': {'key': lambda x: x.avg_rating, 'reverse': False}   # Worst rating.
    }
    # Get attribute values of all products of this type.
    ProductSpecific_model = get_product_specific_model(product_type)
    if ProductSpecific_model is None:
        return HttpResponseNotFound("Not found.")
    attributes = ProductSpecific_model.get_attribute_values()
    attribute_names = ProductSpecific_model.get_lookup_names()
    # Filter products_specific with request.GET parameters
    filtered_products_specific = ProductSpecific_model.filter_with_query_dict(request.GET)
    filtered_products_ids = filtered_products_specific.values_list('product', flat=True).distinct()
    filtered_products = Product.objects.filter(id__in=filtered_products_ids)
    # Filter products price.
    try:
        price_from = float(request.GET.get('price_from', ''))
    except ValueError:
        price_from = 0
    try:
        price_to = float(request.GET.get('price_to', ''))
    except ValueError:
        price_to = math.inf
    filtered_products = [product for product in filtered_products if price_from <= product.current_price <= price_to]
    # Ordering products
    ordering = request.GET.get('order', '1')
    filtered_products.sort(**ORDERING.get(ordering, ORDERING['1']))
    type_name = PRODUCT_TYPES[str(product_type)]
    context = {
        'title': f"Category {type_name}s",
        'products': filtered_products,
        'type_name': type_name,
        'attributes': attributes,
        'attribute_names': attribute_names
    }
    return render(request, 'products/product_type.html', context)

products/templates/products/cart.html
{% extends 'base.html' %}

{% block content %}
    <h1 class="my-4">Cart</h1>
    {% if cart_products %}
    <ul class="list-group">
        {% for object, amount in cart_products %}
          <li class="list-group-item d-flex list-group-item-info">
                <span class="flex-grow-1"><a href="{{object.url_specific}}">{{object}} <b>{{object.product.current_price}}</b></a></span>
                <a><span class="badge bg-primary rounded-pill">{{amount}}</span></a>
                <a href="{% url 'products:add-cart' object.product.id object.id %}"><span class="badge bg-primary rounded-pill">+</span></a>
                <a href="{% url 'products:remove-cart' object.product.id object.id %}"><span class="badge bg-primary rounded-pill">-</span></a>
          </li>
        {% endfor %}
    </ul>
    <div class="mt-4">
        <h2>Total: {{cart_value}} </h2>
    </div>
    <a href="{% url 'orders:data' %}"><button class="btn btn-primary my-4 " type="button">Order</button></a>
    <a href="{% url 'products:clear-cart' %}"><button class="btn btn-danger my-4 " type="button">Clear cart</button></a>
    {% else %}
    <p>Your cart is empty</p>
    {% endif %}
    <a href="{% url 'pages:home' %}" class="btn btn-secondary">Home</a>
{% endblock %}

products/templates/products/product_card.html
<a class="link-offset-2 link-underline link-underline-opacity-0" href="{{ product.get_absolute_url }}">
    <div class="card text-bg-secondary mb-3 border-dark" style="width: 18rem;" >
        {% if product.images.first %}
            <img src="{{ product.main_image_object.img.url }}" style="height: 20rem; background-color:white;" class="img-card" alt="Main Image">
        {% endif %}
        <div class="card-body">
            <h5 class="card-title">{{product.name}}</h5>
            <div class="card-text fs-6">{{product.description|truncatechars:28}}</div>
            {% if product.discount %}
              <div><s class="fs-7">{{product.price}}</s> <b class="fs-4">{{product.current_price}}</b></div>
              <div>Now {{product.discount}}% cheaper!</div>
            {% else %}
                <div class="fs-4">{{product.price}}</div>
            {% endif %}
            <div class="star-rating"
                 style="background-image: linear-gradient(to right, gold 0%, gold {{product.rating_percentage}}%,
                 transparent {{product.rating_percentage}}%, transparent 100%);"></div>
            <div style="font-size: 12px;">{{product.number_of_ratings}} rating{{ product.number_of_ratings|pluralize }}</div>
        </div>
    </div>
</a>

products/templates/products/product_detail.html
{% extends 'base.html' %}
{% load humanize %}
{% load replace %}
{% load get_item %}
{% block content %}

    <div class="card mt-5">
      <h5 class="card-header">{{product.name}}</h5>

      <div class="card-body" id ="card">
        <div class="star-rating"
           style="background-image: linear-gradient(to right, gold 0%, gold {{product.rating_percentage}}%,
           transparent {{product.rating_percentage}}%, transparent 100%); font-size: 25px;"></div>
        <div style="font-size: 10px;">{{product.number_of_ratings}} rating{{ product.number_of_ratings|pluralize }}</div>
        <!-- Big Image -->
        {% if product.images.first %}
          <figure>
            <img class="my-2" id='currentImg' src="{{ product.main_image_object.img.url}}" class="img-fluid" alt="Picture">
            <figcaption id='currentText'>{{ product.main_image_object.description }}</figcaption>
          </figure>
        {% endif %}
        {% if product.discount %}
          <div class="mb-3 card-title"> <s class="fs-5">{{product.price}}</s>  <b class="fs-3">{{product.current_price}}</b> </div>
          <div class="fs-5 mb-3" >Now {{product.discount}}% cheaper!</div>
        {% else %}
          <div class="fs-3 mb-3 card-title"> <b>{{product.price}}</b> </div>
        {% endif %}
        <!-- Thumbnails -->
        {% for image in images %}
          {% if image.thumbnail %}
            <!--Add border to the first image.-->
            {% if forloop.first %}
                <img id="thumbnail_{{image.id}}" src="{{image.thumbnail.url}}" class="img-thumbnail main-thumbnail"
                 alt="thumbnail"
                 onclick="showImage('{{image.img.url}}','{{image.description}}','thumbnail_{{image.id}}');">
            {% else %}
                <img id="thumbnail_{{image.id}}" src="{{image.thumbnail.url}}" class="img-thumbnail" alt="thumbnail"
                 onclick="showImage('{{image.img.url}}','{{image.description}}','thumbnail_{{image.id}}');">
            {% endif %}
          {% endif %}
        {% endfor %}
        <!-- Specific attributes -->
        <!-- Form created based on attributes of available specific products, submitted every time attribute value is
         changed, showing available products with selected attributes -->
        <form method="GET" action="#form" id="form" class="my-4">
          {% for attribute, values in attributes.items %}
            <label for="{{attribute}}" class="form-label">{{attribute_names|get_dict:attribute|capfirst|replace:"_"}}:</label>
            <select class="form-select" name="{{attribute}}" id="{{attribute}}" onchange="this.form.submit()">
              <option value="">No selection</option>
              {% for value in values %}
                  <option value="{{value}}" {% selected request.GET attribute value%}>{{value}}</option>
              {% endfor %}
            </select>
          <br>
          {% endfor %}
         <!-- Add to cart button - showed when all attributes are selected -->
          {% if all_selected %}
            <button class="btn btn-primary" type="button" onclick="addCart()">Add to cart</button>
          {% endif %}
            <a href="{{product.get_absolute_url}}/rate"><button class="btn btn-primary" type="button">Rate product</button></a>
          {% if request.GET %}
            <a href="{{request.path}}"><button class="btn btn-secondary" type="button">Reset selections</button></a>
          {% endif %}
          <br>
        </form>
        <p class="card-text my-4">{{product.description}}</p>
        <!-- Naviagtion -->
        <button onclick="history.back()" class="btn btn-secondary" type="button">Go back</button>

        <!-- Comments -->
        {% if comments %}
          <div class="my-3" id="comments">
            <h5 style="display: inline-block;">Product comments:</h5>
              <div class="dropdown float-end" style="display: inline-block;">
                <!-- Ordering-->
                <form action="#comments" id="form2">
                  <select class="form-select" name="order" id="order" onchange="addOrder()" >
                    <option value="" selected>Order by</option>
                    <option value="1">Newest</option>
                    <option value="2">Oldest</option>
                    <option value="3">Highest rating</option>
                    <option value="4">Lowest rating</option>
                  </select>
                </form>
              </div>

            {% for comment in comments %}
              <div class="card my-3">
                <div class="card-header d-flex">
                  <div class="flex-grow-1">{{comment.user}}</div> <div class="justify-content-end">{{comment.created|naturaltime}}</div>
                </div>
                <div class="card-body">
                  <h5 class="card-title">Rating: <div class="star-rating"
                     style="background-image: linear-gradient(to right, gold 0%, gold {{comment.value_percentage}}%,
                     transparent {{comment.value_percentage}}%, transparent 100%);"></div></h5>
                  <p class="card-text">{{comment.comment}}</p>
                  {% if comment.user == request.user %}
                    <a href="{% url 'products:rate' product.id%}"><button class="btn btn-secondary" type="button">Edit comment</button></a>
                  {% endif %}
                </div>
              </div>
            {% endfor %}
          </div>
        {% endif %}
      </div>
    </div>


<!-- Change picture after clicking on thumbnail.-->
<script type="text/javascript">
function showImage(imgPath, imgText, thumbClicked) {
    var curImage = document.getElementById('currentImg');
    var curText = document.getElementById('currentText');
    var thumb = document.getElementById(thumbClicked);
    var all_thumbs = document.getElementById("card").getElementsByClassName("img-thumbnail");
    for (let i = 0; i < all_thumbs.length; i++) {
        all_thumbs[i].classList.remove('border');
        all_thumbs[i].classList.remove('border-info');
    }
    thumb.classList.add('border');
    thumb.classList.add('border-info');
    curImage.src = imgPath;
    curText.innerText = imgText;
 }
</script>

<!--Set main thumbnail after page is loaded.-->
<script type="text/javascript">
document.addEventListener("DOMContentLoaded", () => {
  var mainThumb = document.getElementById("card").getElementsByClassName("main-thumbnail");
  if (mainThumb.length >0) {
    mainThumb[0].classList.add('border');
    mainThumb[0].classList.add('border-info');
    }
});
</script>

<!--Add additional hidden field to form and change action when add to cart is clicked.-->
<script type="text/javascript">
function addCart(){
  var form = document.getElementById('form');
  const hiddenField = document.createElement('input');
  hiddenField.type = 'hidden';
  hiddenField.name = 'add_cart';
  hiddenField.value = '1';
  form.appendChild(hiddenField);
  document.body.appendChild(form);
  form.action = '#';
  form.submit()
}
</script>

<script>
  function addOrder(){
  var order = document.getElementById('order');
  var currentURL = window.location.href;
  var queryString = window.location.search;
  var newParams = new URLSearchParams(queryString);
  newParams.set('order', order.value);
  var newQueryString = newParams.toString();
  var newURL = currentURL.split('?')[0] + '?' + newQueryString + '#comments';
  window.history.replaceState(null, '', newURL);
  window.location.reload();
}
</script>
{% endblock %}

products/templates/products/product_rate_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<h1 class="my-4">Rate product:</h1>
<div class="mt-4">
    <form method="POST">
        {% csrf_token %}
        {{form|crispy}}
        <button type="submit" class="btn btn-primary my-4">Submit</button>
        <button onclick="history.back()" class="btn btn-secondary" type="button">Go back</button>
    </form>
</div>
{% endblock %}

products/templates/products/product_type.html
{% extends 'base.html' %}
{% load replace %}
{% load get_item %}
{% block sidebar%}
<div class="container-fluid">
    <div class="row flex-nowrap">
        <div class="col-auto col-md-3 col-xl-2 px-sm-2 px-0 bg-dark" >
            <div class="d-flex flex-column align-items-center align-items-sm-start px-3 pt-2 text-white min-vh-100">
                <span class="fs-3 d-none d-sm-inline my-3">Filter products</span>
                <ul class="nav nav-pills flex-column mb-sm-auto mb-0 align-items-center align-items-sm-start" id="menu">
                    <form method="GET" id="filter_form">
                        <p><label for="price_from" class="form-label">Price from: </label>
                        <input type="number" step="0.01" min=0 name="price_from" id="price_from"
                        value="{{request.GET.price_from}}"></p>

                        <p><label for="price_from"  class="form-label">Price to:</label>
                        <input type="number" step="0.01" min=0 name="price_to" id="price_to"
                        value="{{request.GET.price_to}}"></p>
                        {% for attribute, values in attributes.items %}
                             <legend class="my-1">{{attribute_names|get_dict:attribute|capfirst|replace:"_"}}</legend>
                            {% for value in values %}
                                     <input type="checkbox" name="{{attribute}}" value="{{value}}"
                                     {% checked request.GET attribute value%}>
                                    &nbsp{{value}} <br>
                            {% endfor %}
                        {% endfor %}
                        <input type="hidden" name="order" value="{{request.GET.order}}">
                        <button type="submit" class="btn btn-secondary my-4" onclick="">Filter</button>
                    </form>
                </ul>
            </div>
        </div>
        <div class="col py-3">
             <div class="container text-center" style="display: inline-block; margin-left:5%">
                {% if products %}
                    <div class="my-4" >
                        <h1 style="display: inline-block;">Products in {{type_name}}s category:</h1>
                        <div class="dropdown float-end" style="display: inline-block; padding: 7px 0;">
                            <form method="GET" id="order_form">
                              <select class="form-select" name="order" id="order" onchange="addOrder()">
                                <option value="" selected>Order by</option>
                                <option value="1">Lowest price</option>
                                <option value="2">Highest price</option>
                                <option value="3">Best ratings</option>
                                <option value="4">Worst ratings</option>
                              </select>
                            </form>
                        </div>
                    </div>

                    <div class="row row-cols-3">
                        {% for product in products %}
                            {% include 'products/product_card.html'%}
                        {% endfor %}
                    </div>
                {% else %}
                    <h1 class="my-2">No products found</h1>
                {% endif %}
                </div>
                    </div>
                </div>
            </div>
<!--Add order variable to url-->
<script>
  function addOrder(){
      var order = document.getElementById('order');
      var currentURL = window.location.href;
      var queryString = window.location.search;
      var newParams = new URLSearchParams(queryString);
      newParams.set('order', order.value);
      var newQueryString = newParams.toString();
      var newURL = currentURL.split('?')[0] + '?' + newQueryString;
      window.history.replaceState(null, '', newURL);
      window.location.reload();
}
</script>

{% endblock %}
{% block content %}

{% endblock %}